import type { Metadata } from 'next'
import './globals.css';
import "primereact/resources/themes/lara-dark-blue/theme.css";
import '/node_modules/primeflex/primeflex.css'; 
import 'primeicons/primeicons.css';

import Navbar from './components/navbar/Navbar'

export const metadata: Metadata = {
  title: "Zachary Burns' Profile",
  description: 'Generated by create next app',  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className='screen'>        
          <Navbar />
          {children}
      </body>
    </html>
  )
}